name: container
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: digitalasset/daml-sdk:2.5.0
      options: --user root
      volumes:
         - /github/home/daml-settlement-app:/github/home/daml-settlement-app
    steps:
         - name: Log the Daml version
           run: |
             daml version
         - name: Checkout
           uses: actions/checkout@v3
           with:
             path: daml-settlement-app
         - name: Run test
           run: |
             cd daml-settlement-app
             ls -al
             daml build
             daml test